# Generated by Django (makemigrations equivalent)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255)),
                ("waid", models.CharField(max_length=32, unique=True, verbose_name="WAID")),
                ("ultima_mensagem", models.TextField(blank=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
                "ordering": ("-atualizado_em",),
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texto", models.TextField()),
                ("direcao", models.CharField(choices=[("in", "Entrada"), ("out", "Saída")], max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Enfileirada"),
                            ("sent", "Enviada"),
                            ("delivered", "Entregue"),
                            ("read", "Lida"),
                            ("failed", "Falha"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "meta_message_id",
                    models.CharField(
                        blank=True,
                        help_text="ID da mensagem na API do WhatsApp (Meta)",
                        max_length=128,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="core.contato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ("timestamp", "id"),
            },
        ),
    ]
